### ISSUE TITLE
No songs updating

### ISSUE THREAD

**Issue by manjarolinuxuser** [DerSchmaik/applemusic_playlist_to_spotify#7]
It is saying that zero songs are updated

![IMG_20230823_163156195~2.jpg](https://github.com/DerSchmaik/applemusic-playlist-to-spotify/assets/138491069/c0e5a910-4c9e-4b26-bb00-7d56fb6a30a6)

**Comment by danihrndzld** [comment]
Did you find a fix?

**Comment by manjarolinuxuser** [comment]
I used a completely different approach

**Comment by flame-princess-is-a-fusion** [comment]
What was the approach? I'm having the same issue, len(songs) is 0

**Comment by Schwegs** [comment]
Mine is also not updating, I would love to know how to fix this

**Comment by sudo-nano** [comment]
Same issue here. Preliminary investigation suggests that Apple has changed the response they give to automated requests (i.e. not a normal browser user agent) so that it's now different from normal browser requests. 

Using inspect element on the webpage for a playlist reveals HTML that should be parsing correctly, but inspecting the response that you get from the python `requests` library or `curl` shows entirely different content. I tried fixing this by faking the user agent, but it was not successful. Apple, unsurprisingly, has better than script kiddie level of automation detection.

I managed to get it barely working by replacing the web request for the Apple Music with a portion where it loads a file with the HTML that I downloaded manually, but this does require you to access each playlist page in your browser and then `Ctrl + S` save it, and then sideload each one of those playlist webpages. 

I suggest that this be fixed either with more advanced user agent faking to trick Apple's site into thinking this program is a normal browser, or changing the page parsing to make it correctly parse the response the website gives to automated requests.

**Comment by aikozim** [comment]
Hi everyone, indeed Apple Music frequently updates how they format song information on their pages. This can sometimes make the script stop working. I think I fixed everything for now, making the script fully functional again. If you see any more problems, feel free to open another issue.

Script working again:
<img width="823" alt="SCR-20231203-qrsy" src="https://github.com/DerSchmaik/applemusic-playlist-to-spotify/assets/47828495/04825a09-5846-4bf3-8847-e590d10fbd0a">
